title: "Compedia"
description: "AI-powered platform for company profiles"
# theme: jekyll-theme-architect  # You can change this to other themes like 'jekyll-theme-slate'
remote_theme: cotes2020/jekyll-theme-chirpy
